name: RailsTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium_chrome:
        image: selenium/standalone-chrome
        ports:
          - "4444:4444"
      db:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: password
    env:
      RAILS_ENV: test
      RAILS_TEST_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundle-cache: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-

      # Add or replace test runners here
      - name: Install dependencies(Yarn)
        run: yarn install --check-files

      - name: Install dependencies(Bundler)
        run: bundle install --path vendor/bundle

      # Add or replace database setup steps here
      - name: Set up database configuration
        run: cp config/database.yml.ci config/database.yml

      - name: Debug database configuration
        run: cat config/database.yml

      - name: Set up database schema
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: bin/rails test test/models test/controllers test/system --verbose
