name: RailsTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: password
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.MASTER_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundle-cache: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Add or replace database setup steps here
      - name: Set up database schema
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate

      # Add or replace test runners here
      - name: Install dependencies
        run: |
          bundle install
          yarn install

      - name: Run tests
        run: bin/rails test
